spring:
  application:
    name: api-gateway

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#

  cloud:
    gateway:
      routes:
        - id: user-services
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/**
#          filters:
#            - TokenFilter
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/product/**

        - id: order-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/order/**

server:
  port: 8084

logging:
    level:
      org.springframework.cloud.gateway: DEBUG


